// Copyright (c) All contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Concurrent;
using System.Linq;
using System.Reflection;
using MessagePack.Formatters;
using MessagePack.Internal;

namespace MessagePack.Resolvers
{
    /// <summary>
    /// A resolver that discovers formatters generated by <c>MessagePack.SourceGenerator</c>.
    /// </summary>
    public sealed class SourceGeneratedFormatterResolver : IFormatterResolver
    {
        /// <summary>
        /// The singleton instance that can be used.
        /// </summary>
        public static readonly SourceGeneratedFormatterResolver Instance = new();

        private static readonly ConcurrentBag<IFormatterResolver?> AssemblyResolvers = new();

        static SourceGeneratedFormatterResolver()
        {
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                TryAddResolver(assembly);
            }

            AppDomain.CurrentDomain.AssemblyLoad += (_, e) =>
            {
                TryAddResolver(e.LoadedAssembly);
            };

            static void TryAddResolver(Assembly assembly)
            {
                try
                {
                    if (assembly.GetCustomAttributes<GeneratedAssemblyMessagePackResolverAttribute>().FirstOrDefault() is { } att &&
                        att.ResolverType.GetField("Instance", BindingFlags.Public | BindingFlags.Static)?.GetValue(null) is IFormatterResolver
                            resolver)
                    {
                        AssemblyResolvers.Add(resolver);
                    }
                }
                catch
                {
                    // Ignore
                }
            }
        }

        private SourceGeneratedFormatterResolver()
        {
        }

        /// <inheritdoc/>
        public IMessagePackFormatter<T>? GetFormatter<T>() => FormatterCache<T>.Formatter;

        private static class FormatterCache<T>
        {
            internal static readonly IMessagePackFormatter<T>? Formatter = FindPrecompiledFormatter();

            private static IMessagePackFormatter<T>? FindPrecompiledFormatter()
            {
                foreach (var resolver in AssemblyResolvers)
                {
                    if (resolver?.GetFormatter<T>() is { } f)
                    {
                        return f;
                    }
                }

                return null;
            }
        }
    }
}
